In [2]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
df.head() # df.head(5)

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,English,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,English,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,English,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,English,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD

In [3]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
df['industry'].unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [18]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
data = {"title","revenue"}

In [26]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
print(df.columns)
marvel_movies = df[df['studio'] == 'Marvel Studios']
print(marvel_movies)

Index(['movie_id', 'title', 'industry', 'language', 'release_year',
       'imdb_rating', 'studio', 'budget', 'revenue', 'unit', 'currency'],
      dtype='object')
    movie_id                                        title   industry language  \
1        102  Doctor Strange in the Multiverse of Madness  Hollywood  English
2        103                        Thor: The Dark World   Hollywood  English
3        104                              Thor: Ragnarok   Hollywood  English
4        105                      Thor: Love and Thunder   Hollywood  English
17       125                            Avengers: Endgame  Hollywood  English
18       126                       Avengers: Infinity War  Hollywood  English
19       137           Captain America: The First Avenger  Hollywood  English
20       138          Captain America: The Winter Soldier  Hollywood  English

    release_year  imdb_rating          studio  budget  revenue      unit  \
1           2022          7.0  Marvel Studios   200.0    954.8  Millions
2           2013          6.8  Marvel Studios   165.0    644.8  Millions
3           2017          7.9  Marvel Studios   180.0    854.0  Millions
4           2022          6.8  Marvel Studios   250.0    670.0  Millions
17          2019          8.4  Marvel Studios   400.0   2798.0  Millions
18          2018          8.4  Marvel Studios   400.0   2048.0  Millions
19          2011          6.9  Marvel Studios   216.7    370.6  Millions
20          2014          7.8  Marvel Studios   177.0    714.4  Millions

   currency
1       USD
2       USD
3       USD
4       USD
17      USD
18      USD
19      USD
20      USD

In [32]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
df['revenue'].max()

np.float64(100000.0)

In [31]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
df['revenue'].min()

np.float64(3.1)

In [33]:
df[df['imdb_rating']>8]

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.00,12.5,Billions,INR
5,111,The Shawshank Redemption,Hollywood,English,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD
6,113,Interstellar,Hollywood,English,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD
8,116,Gladiator,Hollywood,English,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD
10,118,It's a Wonderful Life,Hollywood,English,1946,8.6,Liberty Films,3.18,3.3,Millions,USD
12,120,The Godfather,Hollywood,English,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD
13,121,The Dark Knight,Hollywood,English,2008,9.0,Syncopy,185.00,1006.0,Millions,USD
14,122,Schindler's List,Hollywood,English,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD
15,123,Jurassic Park,Hollywood,English,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD
16,124,Parasite,Hollywood,English,2019,8.5,NaN,15.50,263.1,Millions,USD
17,125,Avengers: Endgame,Hollywood,English,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD
18,126,Avengers: Infinity War,Hollywood,English,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD
22,108,3 Idiots,Bollywood,Hindi,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR
25,128,Taare Zameen Par,Bollywood,Hindi,2007,8.3,NaN,120.00,1350.0,Millions,INR
26,129,Munna Bhai M.B.B.S.,Bollywood,Hindi,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR
27,130,PK,Bollywood,Hindi,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR
29,135,The Kashmir Files,Bollywood,Hindi,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR
30,136,Bajrangi Bhaijaan,Bollywood,Hindi,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR
32,140,Shershaah,Bollywood,Hindi,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR
33,127,Pather Panchali,Bollywood,Bengali,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR

In [43]:
df[df['imdb_rating']>4],[df['imdb_rating']<8]

(    movie_id                                        title   industry language  \
 0        101                             K.G.F: Chapter 2  Bollywood  Kannada
 1        102  Doctor Strange in the Multiverse of Madness  Hollywood  English
 2        103                        Thor: The Dark World   Hollywood  English
 3        104                              Thor: Ragnarok   Hollywood  English
 4        105                      Thor: Love and Thunder   Hollywood  English
 5        111                     The Shawshank Redemption  Hollywood  English
 6        113                                 Interstellar  Hollywood  English
 7        115                     The Pursuit of Happyness  Hollywood  English
 8        116                                    Gladiator  Hollywood  English
 9        117                                      Titanic  Hollywood  English
 10       118                        It's a Wonderful Life  Hollywood  English
 11       119                                       Avatar  Hollywood  English
 12       120                                The Godfather  Hollywood  English
 13       121                              The Dark Knight  Hollywood  English
 14       122                             Schindler's List  Hollywood  English
 15       123                                Jurassic Park  Hollywood  English
 16       124                                     Parasite  Hollywood  English
 17       125                            Avengers: Endgame  Hollywood  English
 18       126                       Avengers: Infinity War  Hollywood  English
 19       137           Captain America: The First Avenger  Hollywood  English
 20       138          Captain America: The Winter Soldier  Hollywood  English
 21       107                  Dilwale Dulhania Le Jayenge  Bollywood    Hindi
 22       108                                     3 Idiots  Bollywood    Hindi
 23       109                     Kabhi Khushi Kabhie Gham  Bollywood    Hindi
 24       110                             Bajirao Mastani   Bollywood    Hindi
 25       128                             Taare Zameen Par  Bollywood    Hindi
 26       129                          Munna Bhai M.B.B.S.  Bollywood    Hindi
 27       130                                           PK  Bollywood    Hindi
 29       135                            The Kashmir Files  Bollywood    Hindi
 30       136                            Bajrangi Bhaijaan  Bollywood    Hindi
 32       140                                    Shershaah  Bollywood    Hindi
 33       127                              Pather Panchali  Bollywood  Bengali
 34       132                    Pushpa: The Rise - Part 1  Bollywood   Telugu
 35       133                                          RRR  Bollywood   Telugu
 36       134                     Baahubali: The Beginning  Bollywood   Telugu

     release_year  imdb_rating                     studio    budget   revenue  \
 0           2022          8.4              Hombale Films      1.00      12.5
 1           2022          7.0             Marvel Studios    200.00     954.8
 2           2013          6.8             Marvel Studios    165.00     644.8
 3           2017          7.9             Marvel Studios    180.00     854.0
 4           2022          6.8             Marvel Studios    250.00     670.0
 5           1994          9.3  Castle Rock Entertainment     25.00      73.3
 6           2014          8.6      Warner Bros. Pictures    165.00     701.8
 7           2006          8.0          Columbia Pictures     55.00     307.1
 8           2000          8.5       Universal Pictures      103.00     460.5
 9           1997          7.9         Paramount Pictures    200.00    2202.0
 10          1946          8.6              Liberty Films      3.18       3.3
 11          2009          7.8           20th Century Fox    237.00    2847.0
 12          1972          9.2         Paramount Pictures      7.20     291.0
 13          2008          9.0                    Syncopy    185.00    1006.0
 14          1993          9.0         Universal Pictures     22.00     322.2
 15          1993          8.2         Universal Pictures     63.00    1046.0
 16          2019          8.5                        NaN     15.50     263.1
 17          2019          8.4             Marvel Studios    400.00    2798.0
 18          2018          8.4             Marvel Studios    400.00    2048.0
 19          2011          6.9             Marvel Studios    216.70     370.6
 20          2014          7.8             Marvel Studios    177.00     714.4
 21          1995          8.0             Yash Raj Films    400.00    2000.0
 22          2009          8.4         Vinod Chopra Films    550.00    4000.0
 23          2001          7.4         Dharma Productions    390.00    1360.0
 24          2015          7.2                        NaN      1.40       3.5
 25          2007          8.3                        NaN    120.00    1350.0
 26          2003          8.1   Vinod Chopra Productions    100.00     410.0
 27          2014          8.1         Vinod Chopra Films    850.00    8540.0
 29          2022          8.3                Zee Studios    250.00    3409.0
 30          2015          8.1          Salman Khan Films    900.00   11690.0
 32          2021          8.4         Dharma Productions    500.00     950.0
 33          1955          8.3  Government of West Bengal  70000.00  100000.0
 34          2021          7.6        Mythri Movie Makers      2.00       3.6
 35          2022          8.0          DVV Entertainment      5.50      12.0
 36          2015          8.0           Arka Media Works      1.80       6.5

          unit currency
 0    Billions      INR
 1    Millions      USD
 2    Millions      USD
 3    Millions      USD
 4    Millions      USD
 5    Millions      USD
 6    Millions      USD
 7    Millions      USD
 8    Millions      USD
 9    Millions      USD
 10   Millions      USD
 11   Millions      USD
 12   Millions      USD
 13   Millions      USD
 14   Millions      USD
 15   Millions      USD
 16   Millions      USD
 17   Millions      USD
 18   Millions      USD
 19   Millions      USD
 20   Millions      USD
 21   Millions      INR
 22   Millions      INR
 23   Millions      INR
 24   Billions      INR
 25   Millions      INR
 26   Millions      INR
 27   Millions      INR
 29   Millions      INR
 30   Millions      INR
 32   Millions      INR
 33  Thousands      INR
 34   Billions      INR
 35   Billions      INR
 36   Billions      INR  ,
 [0     False
  1      True
  2      True
  3      True
  4      True
  5     False
  6     False
  7     False
  8     False
  9      True
  10    False
  11     True
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19     True
  20     True
  21    False
  22    False
  23     True
  24     True
  25    False
  26    False
  27    False
  28    False
  29    False
  30    False
  31     True
  32    False
  33    False
  34     True
  35    False
  36    False
  Name: imdb_rating, dtype: bool])

In [44]:
df[df['release_year']>2018],[df['release_year']<2022]

(    movie_id                                        title   industry language  \
 0        101                             K.G.F: Chapter 2  Bollywood  Kannada
 1        102  Doctor Strange in the Multiverse of Madness  Hollywood  English
 4        105                      Thor: Love and Thunder   Hollywood  English
 16       124                                     Parasite  Hollywood  English
 17       125                            Avengers: Endgame  Hollywood  English
 29       135                            The Kashmir Files  Bollywood    Hindi
 32       140                                    Shershaah  Bollywood    Hindi
 34       132                    Pushpa: The Rise - Part 1  Bollywood   Telugu
 35       133                                          RRR  Bollywood   Telugu

     release_year  imdb_rating               studio  budget  revenue      unit  \
 0           2022          8.4        Hombale Films     1.0     12.5  Billions
 1           2022          7.0       Marvel Studios   200.0    954.8  Millions
 4           2022          6.8       Marvel Studios   250.0    670.0  Millions
 16          2019          8.5                  NaN    15.5    263.1  Millions
 17          2019          8.4       Marvel Studios   400.0   2798.0  Millions
 29          2022          8.3          Zee Studios   250.0   3409.0  Millions
 32          2021          8.4   Dharma Productions   500.0    950.0  Millions
 34          2021          7.6  Mythri Movie Makers     2.0      3.6  Billions
 35          2022          8.0    DVV Entertainment     5.5     12.0  Billions

    currency
 0       INR
 1       USD
 4       USD
 16      USD
 17      USD
 29      INR
 32      INR
 34      INR
 35      INR  ,
 [0     False
  1     False
  2      True
  3      True
  4     False
  5      True
  6      True
  7      True
  8      True
  9      True
  10     True
  11     True
  12     True
  13     True
  14     True
  15     True
  16     True
  17     True
  18     True
  19     True
  20     True
  21     True
  22     True
  23     True
  24     True
  25     True
  26     True
  27     True
  28     True
  29    False
  30     True
  31     True
  32     True
  33     True
  34     True
  35    False
  36     True
  Name: release_year, dtype: bool])

In [45]:
df.describe()

         movie_id  release_year  imdb_rating        budget        revenue
count   37.000000     37.000000    36.000000     37.000000      37.000000
mean   121.297297   2007.027027     7.919444   2084.975135    4117.135135
std     11.763562     17.657995     1.204947  11477.487145   16372.462682
min    101.000000   1946.000000     1.900000      1.000000       3.100000
25%    111.000000   2001.000000     7.800000     15.500000     263.100000
50%    122.000000   2014.000000     8.100000    165.000000     701.800000
75%    131.000000   2018.000000     8.400000    250.000000    2000.000000
max    140.000000   2022.000000     9.300000  70000.000000  100000.000000

In [71]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
df['new_column_name'] = 2025-df['release_year']
df

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency,new_column_name
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,English,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,3
2,103,Thor: The Dark World,Hollywood,English,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,12
3,104,Thor: Ragnarok,Hollywood,English,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,8
4,105,Thor: Love and Thunder,Hollywood,English,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,3
5,111,The Shawshank Redemption,Hollywood,English,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,31
6,113,Interstellar,Hollywood,English,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,11
7,115,The Pursuit of Happyness,Hollywood,English,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,19
8,116,Gladiator,Hollywood,English,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,25
9,117,Titanic,Hollywood,English,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,28
10,118,It's a Wonderful Life,Hollywood,English,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,79
11,119,Avatar,Hollywood,English,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,16
12,120,The Godfather,Hollywood,English,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,53
13,121,The Dark Knight,Hollywood,English,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,17
14,122,Schindler's List,Hollywood,English,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,32
15,123,Jurassic Park,Hollywood,English,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,32
16,124,Parasite,Hollywood,English,2019,8.5,NaN,15.50,263.1,Millions,USD,6
17,125,Avengers: Endgame,Hollywood,English,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,6
18,126,Avengers: Infinity War,Hollywood,English,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,7
19,137,Captain America: The First Avenger,Hollywood,English,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,14
20,138,Captain America: The Winter Soldier,Hollywood,English,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,11
21,107,Dilwale Dulhania Le Jayenge,Bollywood,Hindi,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,30
22,108,3 Idiots,Bollywood,Hindi,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,16
23,109,Kabhi Khushi Kabhie Gham,Bollywood,Hindi,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,24
24,110,Bajirao Mastani,Bollywood,Hindi,2015,7.2,NaN,1.40,3.5,Billions,INR,10
25,128,Taare Zameen Par,Bollywood,Hindi,2007,8.3,NaN,120.00,1350.0,Millions,INR,18
26,129,Munna Bhai M.B.B.S.,Bollywood,Hindi,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,22
27,130,PK,Bollywood,Hindi,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,11
28,131,Sanju,Bollywood,Hindi,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,7
29,135,The Kashmir Files,Bollywood,Hindi,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,3
30,136,Bajrangi Bhaijaan,Bollywood,Hindi,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,10
31,139,Race 3,Bollywood,Hindi,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,7
32,140,Shershaah,Bollywood,Hindi,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,4
33,127,Pather Panchali,Bollywood,Bengali,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,70
34,132,Pushpa: The Rise - Part 1,Bollywood,Telugu,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,4
35,133,RRR,Bollywood,Telugu,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,3
36,134,Baahubali: The Beginning,Bollywood,Telugu,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,10

In [77]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
df['profit'] = df['revenue'] - df['budget']
print(df[['revenue', 'budget', 'profit']])

     revenue    budget    profit
0       12.5      1.00     11.50
1      954.8    200.00    754.80
2      644.8    165.00    479.80
3      854.0    180.00    674.00
4      670.0    250.00    420.00
5       73.3     25.00     48.30
6      701.8    165.00    536.80
7      307.1     55.00    252.10
8      460.5    103.00    357.50
9     2202.0    200.00   2002.00
10       3.3      3.18      0.12
11    2847.0    237.00   2610.00
12     291.0      7.20    283.80
13    1006.0    185.00    821.00
14     322.2     22.00    300.20
15    1046.0     63.00    983.00
16     263.1     15.50    247.60
17    2798.0    400.00   2398.00
18    2048.0    400.00   1648.00
19     370.6    216.70    153.90
20     714.4    177.00    537.40
21    2000.0    400.00   1600.00
22    4000.0    550.00   3450.00
23    1360.0    390.00    970.00
24       3.5      1.40      2.10
25    1350.0    120.00   1230.00
26     410.0    100.00    310.00
27    8540.0    850.00   7690.00
28       5.9      1.00      4.90
29    3409.0    250.00   3159.00
30   11690.0    900.00  10790.00
31       3.1      1.80      1.30
32     950.0    500.00    450.00
33  100000.0  70000.00  30000.00
34       3.6      2.00      1.60
35      12.0      5.50      6.50
36       6.5      1.80      4.70

In [90]:
import pandas as pd
df = pd.read_csv("movies_data.csv")
df
df['revenue'].max()

np.float64(100000.0)